#!/bin/sh

exit_with_err() {
	echo "Invalid argument: $1"
	exit 1
}

[ "$1" = "on" ] || [ "$1" = "off" ] || exit_with_err $1

displays=$(wlr-randr | grep "^[^ ]" | cut -d ' ' -f 1)
args=""

for display in $displays; do
	[ "$2" = "-v" ] && echo "Turning $1: $display"
	args="$args --output $display --$1"
done

wlr-randr $args
